DROP DATABASE IF EXISTS `DB_Fort`;
CREATE DATABASE `DB_Fort`; 
USE `DB_Fort`;

CREATE TABLE DB_Fort.d_Pessoa(
    ID_PESSOA INT AUTO_INCREMENT PRIMARY KEY,
    NM_PESSOA VARCHAR(45) NOT NULL
);

CREATE TABLE DB_Fort.d_Loja(
    ID_LOJA INT AUTO_INCREMENT PRIMARY KEY,
    DS_NOME VARCHAR(45) NOT NULL,
    DS_UF VARCHAR(45) NOT NULL,
    DS_CIDADE VARCHAR(45) NOT NULL,
    DS_EMPRESA VARCHAR(45) NOT NULL,
    NU_CEP INT NOT NULL
);

CREATE TABLE DB_Fort.d_Tempo(
    ID_TEMPO INT AUTO_INCREMENT PRIMARY KEY,
    DT_REF DATETIME NOT NULL,
    NU_SEMANA INT NOT NULL,
    NU_MES INT NOT NULL,
    NU_TRIMESTRE INT NOT NULL,
    NU_SEMESTRE INT NOT NULL,
    NU_ANO INT NOT NULL
);

CREATE TABLE DB_Fort.f_Vendas(
    ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    VL_VENDA INT NOT NULL,
    NU_VENDA INT NOT NULL,
    VL_LUCRO INT NOT NULL,
    VL_CUSTO INT NOT NULL,
    ID_LOJA INT NOT NULL,
    ID_TEMPO INT NOT NULL,
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_LOJA) REFERENCES DB_Fort.d_Loja(ID_LOJA),
    FOREIGN KEY (ID_TEMPO) REFERENCES DB_Fort.d_Tempo(ID_TEMPO),
    FOREIGN KEY (ID_PESSOA) REFERENCES DB_Fort.d_Pessoa(ID_PESSOA)
);